---
title: "interact_vis"
author: "Rui Miao"
date: '2022-04-08'
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, eval = TRUE)
```

# Interactive visuals

```{r setup, include=FALSE}
library(dplyr)
library(janitor)
library(plotly)

data <- read.csv("./Levels_Fyi_Salary_Data.csv")
data <- data %>%  clean_names()
``` 

```{r include=FALSE}
summary_com <- data %>%
  filter(title == "Data Scientist") %>% 
  group_by(company) %>% 
  summarise(count = n(),
            mean_salary = mean(totalyearlycompensation),
            mean_exp = mean(yearsofexperience),
            mean_com = mean(yearsatcompany))
```

```{r include=FALSE}
summary_exp <- data %>% 
  filter(title== "Data Scientist") %>% 
  group_by(company, yearsofexperience) %>% 
  summarise(count = n(),
            mean_salary = mean(totalyearlycompensation))
```

```{r include=FALSE}
summary_yr_com <- data %>% 
  filter(title== "Data Scientist") %>% 
  group_by(company, yearsatcompany) %>% 
  summarise(count = n(),
            mean_salary = mean(totalyearlycompensation))
```


```{r include=FALSE}

p1_scatter <- summary_com %>% 
  plot_ly(x = ~mean_com, y = ~mean_salary,
          type = 'scatter', 
          mode = 'markers', 
          color = ~company,
          size = ~count, 
          sizes = c(5, 70), 
          marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(company, ":", sep=""), 
                         paste(" Total yearly compensation: $", 
                               mean_salary, sep=""), 
                         sep = "<br>")) %>%
  layout(title = "Year at company vs. Average total yearly compensation",
                  yaxis = list(title = "Average Total yearly compensation"), xaxis = list(title = "Year at company"),
         hovermode = "compare")

p2_scatter <- summary_com %>%
  plot_ly(x = ~mean_exp, y = ~mean_salary,
          type = 'scatter', 
          mode = 'markers', 
          color = ~company,
          size = ~count, 
          sizes = c(5, 70), 
          marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(company, ":", sep=""), 
                         paste("Average total yearly compensation: ", mean_salary, sep=""), 
                         sep = "<br>")) %>%
  layout(title = "Year of experience vs. Average total yearly compensation",
                  yaxis = list(title = "Average total yearly compensation"), xaxis = list(title = "Year of experience"),
         hovermode = "compare")

p3_lines <- summary_exp %>%
  plot_ly(x = ~yearsofexperience,
          y = ~mean_salary,
          color = ~company,
          type = "scatter",
          mode = "lines",
          name = ~company)

p4_lines <- summary_yr_com %>%
  plot_ly(x = ~yearsatcompany,
          y = ~mean_salary,
          color = ~company,
          type = "scatter",
          mode = "lines",
          name = ~company)
```

# a set of plots {.tabset}

## first plot

```{r p1, echo=FALSE}
p1_scatter
```

## second plot

```{r p2}
p2_scatter
```

## Third plot
```{r}
p3_lines
```

## Forth plot
```{r}
p4_lines
```

# more information
lorem ipsum
